# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-04 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mango_memory.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('private', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('never', 'never'), ('daily', 'daily'), ('bidaily', 'bidaily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('bimonthly', 'bimonthly')], default=('never', 'never'), max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', mango_memory.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, null=True)),
                ('release', models.CharField(max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048, null=True)),
                ('latest_release', models.CharField(max_length=128, null=True)),
                ('author', models.CharField(default='', max_length=128)),
                ('relevant_image_url', models.URLField(max_length=512, null=True)),
                ('manga_updates_url', models.URLField(max_length=512, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mango_memory.Manga'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
