# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
