# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161205_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='related_names',
            field=models.TextField(null=True),
        ),
    ]
