# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_emailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='translator',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='translator_url',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_frequency',
            field=models.CharField(choices=[('never', 'never'), ('daily', 'daily'), ('bidaily', 'bidaily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('bimonthly', 'bimonthly')], default='never', max_length=32),
        ),
    ]
